# Generated by Django 4.0 on 2022-01-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elegirrespuesta',
            old_name='correcto',
            new_name='correcta',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='correct',
            new_name='correcta',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='question',
            new_name='pregunta',
        ),
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUser',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Quiz.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Texto de la pregunta'),
        ),
    ]
