# Generated by Django 4.0 on 2022-01-17 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_rename_correcto_elegirrespuesta_correcta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Quiz.quizusuario'),
        ),
    ]
